version: "3.8"

services:
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    networks:
      - app-network
    depends_on:
      - mongo-auth
    environment:
      - MONGO_URL=mongodb://mongo-auth:27017/authdb

  mongo-auth:
    image: mongo:6
    networks:
      - app-network
    volumes:
      - mongo-auth-data:/data/db

  messaging:
    build:
      context: ./messaging
      dockerfile: Dockerfile
    networks:
      - app-network
    depends_on:
      - mongo-messaging
    environment:
      - MONGO_URL=mongodb://mongo-messaging:27017/messagingdb

  mongo-messaging:
    image: mongo:6
    networks:
      - app-network
    volumes:
      - mongo-messaging-data:/data/db

  storage:
    build:
      context: ./storage
      dockerfile: Dockerfile
    networks:
      - app-network
    depends_on:
      - mongo-storage
    environment:
      - MONGO_URL=mongodb://mongo-storage:27017/storagedb

  mongo-storage:
    image: mongo:6
    networks:
      - app-network
    volumes:
      - mongo-storage-data:/data/db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - auth
      - messaging
      - storage
    networks:
      - app-network
    restart: unless-stopped
volumes:
  mongo-auth-data:
  mongo-messaging-data:
  mongo-storage-data:

networks:
  app-network:
    driver: bridge
