version: "3.8"

services:
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    networks:
      - app-network
    depends_on:
      - mongo-auth
    env_file:
      - .env
    environment:
      - MONGO_HOST=${MONGO_HOST_AUTH}
      - MONGO_PORT=${MONGO_PORT_AUTH}
      - MONGO_DATABASE=${MONGO_DATABASE_AUTH}

  mongo-auth:
    image: mongo:latest
    networks:
      - app-network
    volumes:
      - mongo-auth-data:/data/db

  models:
    build:
      context: ./models
      dockerfile: Dockerfile
    networks:
      - app-network
    depends_on:
      - mongo-models
    env_file:
      - .env
    environment:
      - MONGO_HOST=${MONGO_HOST_MODELS}
      - MONGO_PORT=${MONGO_PORT_MODELS}
      - MONGO_DATABASE=${MONGO_DATABASE_MODELS}

  mongo-models:
    image: mongo:latest
    networks:
      - app-network
    volumes:
      - mongo-models-data:/data/db

  storage:
    build:
      context: ./storage
      dockerfile: Dockerfile
    networks:
      - app-network
    depends_on:
      - mongo-storage
    env_file:
      - .env
    environment:
      - MONGO_HOST=${MONGO_HOST_STORAGE}
      - MONGO_PORT=${MONGO_PORT_STORAGE}
      - MONGO_DATABASE=${MONGO_DATABASE_STORAGE}

  mongo-storage:
    image: mongo:latest
    networks:
      - app-network
    volumes:
      - mongo-storage-data:/data/db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - auth
      - models
      - storage
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mongo-auth-data:
  mongo-models-data:
  mongo-storage-data:

networks:
  app-network:
    driver: bridge
